# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    filter_sets:

        profile:
            quality: 75
            filters:

                thumbnail: { size: [400, 400], mode: outbound, allow_upscale: true }

        blog:
            quality: 75
            filters:

                thumbnail: { size: [600, 400], mode: outbound, allow_upscale: true }

        avatar:
            quality: 75
            filters:

                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }

