vich_uploader:
    db_driver: orm

    mappings:
        pictures:
            uri_prefix: /images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
